### ISSUE TITLE
Comment Layout Lost on Rewrite

### ISSUE THREAD

**Issue by bmw** [DiffSK/configobj#108]
I use `configobj` for my project and noticed that comment layout is lost when writing the configuration file. For a trivial example, suppose you have the config file:
```
foo = bar   # My comments
answer = 42 # are lined up
```
After running the following code:
```
import configobj
configobj.ConfigObj('test.conf').write()
```
The contents of the configuration file are:
```
foo = bar# My comments
answer = 42# are lined up
```
Can preserving the formatting of config files be added as a feature to `configobj`?

**Comment by EliAndrewC** [comment]
I certainly have no objection to preserving whitespace in that way, though without diving into the internals I'm not sure how much work it would be.  A pull request would certainly be appreciated!  If not then we'll at least keep this on the backlog.

**Comment by jhermann** [comment]
Whitespace is now preserved, there are a few subtle differences:

* trailing whitespace is now a "comment" (and gets replayed); this can be easily changed if someone sees that as a breaking change.
* no comment is now an empty string, previously it could be that or ``None`` (if you code expects exactly None instead of "non-truth", it is fragile and needs to be fixed).

**Comment by bmw** [comment]
That's great! Do you have a plan for when this will be included in a PyPI release?
