### ISSUE TITLE
Lists of length 1

### ISSUE THREAD

**Issue by Koris** [DiffSK/configobj#112]
When specifying in a configspec that a list can have a length of one:

testItem = list(1, 2, default=list('test','test'))

A comma has to be added in the config even while there is only one item in the list:

testItem = test,
--> works

testItem = test
--> doesn't work

This is confusing for the user of the config, especially because you don't add a comma at the end of a regular multi-item list.

**Comment by EliAndrewC** [comment]
This was by design when the feature was originally implemented, I believe for the following reasons:
- It mirrors how Python works.  If you say ``x = 'foo'`` then ``x`` will be a string, but if you say ``x = 'foo',`` then x will be a tuple.
- In general, explicit is better than implicit.  If someone defines a value a particular way in their config file, I think the original implementors might have considered it bad form to silently coerce it into a different data type.

With that being said, I think I personally agree with this request to do the automatic coercion, for a few reasons:
- We already do type coercion in other cases.  For example, if you define ``foo = integer`` in your specfile and then say ``foo = "5"`` then ``foo`` will be converted to an integer.  Converting to a list doesn't seem any different from that.
- As @Koris points out, this is confusing to newcomers.  I've definitely seem people bitten by it at my job, where the people editing the config files might not know Python, so the whole "trailing comma makes a tuple" logic is foreign to them and not familiar at all.
- This change would be backwards-compatible in the sense that no currently-valid config file would behave any differently after this change.

I don't know when I'll personally have the time to do any real work on ConfigObj next, but I'd definitely be open to a Pull Request implementing this feature.

**Comment by Koris** [comment]
Ah, but I've overlooked the force_list standard check, I'm sorry. This solves the issue I have. I think one or two sentences more in the documentation would have avoided the question.
