### ISSUE TITLE
Any string with a '#' gets parsed incorrectly from the config file

### ISSUE THREAD

**Issue by EvaLovlac3** [DiffSK/configobj#181]
Any string with a '#' gets parsed incorrectly from the config file. For example the string 'some#string' would only be parsed as 'some'. I suspect this because of the way this is passed to the python interpreter? 

I am currently running version 5.0.6 on python 3.6.

**Comment by jhermann** [comment]
Please provide a short example .conf file.

**Comment by EvaLovlac3** [comment]
https://gist.github.com/EvaLovlac3/b597086953436fa008531b52e722763c

**Comment by EvaLovlac3** [comment]
You can mark this resolved, if you wrap it in single quotes it will work. 

EXAMPLE = '#example#example'

**Comment by EvaLovlac3** [comment]
From a member of my irc group. 
You could fix this regex error. 

https://github.com/DiffSK/configobj/blob/master/src/configobj/__init__.py#L1101 and used here https://github.com/DiffSK/configobj/blob/master/src/configobj/__init__.py#L1830, mat.groups() a few lines later will have the comment

**Comment by seajhawk** [comment]
The issue here appears to be that configobj considers everything in your value after the "#" to be an inline comment.
I think your best option is to quote your value as @jhermann recommended. 
Alternatively, if you don't use inline comments, then rather than changing the regex which could lead to unexpected behavior for people who rely on inline comments, I think you should ask for a feature that disables support inline comments.

**Comment by robdennis** [comment]
resolving based on the enclosing quotes working as expected
