### ISSUE TITLE
Please make new release

### ISSUE THREAD

**Issue by kloczek** [DiffSK/configobj#213]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by davetapley** [comment]
_bump_ @robdennis @jhermann

**Comment by robdennis** [comment]
Hi, I confess I don’t actually remember _how_ to make a release these days
since I’ve taken a step back from open source development. Does @jhermann
or the other maintainers feel like they have the right creds/access?

**Comment by sheromon** [comment]
I'm not sure how helpful I'd be, but I'm interested in this. I've been using configobj for... years now (?), and it's been very helpful to me.

**Comment by dvzrv** [comment]
More than a year has passed since this issue has been raised and more than two years have passed since the last commit to this repository has been merged. Given the amount of issues and open PRs I guess it is safe to assume, that configobj is abandonware at this point.

@robdennis @jhermann have you tried reaching out to people for trying to find a more active maintainer for this project? Maybe someone is up for it :)

**Comment by anoduck** [comment]
(I apologize for the customary "dude!" in this statement)

but...

Dude! 
I have finally taken the leap into learning python and have incorporated configobj into all of my "serious" projects. It beats the socks off of configparser. I came here for clarification over the class "Validator", and saw this issue. As previous said, it is the best for configuration parsing IMHO, it needs another release.

Do we need to raise funds or have a candlelight vigil or something?

**Comment by robdennis** [comment]
Hi folks.

In a bit of good news, I'm now working with code that depends on configobj, so supporting went from "find time at home" to something I can spend some time on during the workday.

That being said, I think the project would benefit from someone able to be more responsive to issues being opened, and is more familiar with what an open source project looks like in 2022.

I'll attempt to reach out to @sheromon and see if they're still willing to take on maintenance.

As of now, I think the release process involves manually uploading a distributable to pypi, and so I'd need to give permissions there as well.

Thanks for everyone who still gets value out of this and wants it to stay around. :)

**Comment by robdennis** [comment]
I reached out to the hachyderm.io / mastodon account referenced in the user page. Fingers crossed.

**Comment by sheromon** [comment]
@robdennis Thanks for reaching out! I have been under a rock in a cave (actually my apartment), coughing and blowing my nose and trying many cold medicines over the past couple weeks, but things are getting better lately. I am probably not the maintainer you are looking for, since I don't have much experience, and I don't know how responsive I'd be. I'm happy to attempt to help, though. We can figure out if that even makes sense in another forum, though. I'll shoot you an email as well.

**Comment by anoduck** [comment]
@sheromon Hope you feel better, Cheryl.

**Comment by sheromon** [comment]
@anoduck Aw, thanks!

**Comment by robdennis** [comment]
After speaking with @sheromon here / over email, I think the next step would be for me (a few hours a week, for a few weeks) to put together a release that:

- fixes any identified bugs
- validates that everything works against new python versions since the last release.

And hopefully that's good enough until someone else wants to fork/take this one on.

If anyone wants to take stewardship of the project after that but maybe doesn't feel, then they could volunteer to go through that process with me, and I can at least teach someone how we _were_ doing it back in 2014.

If there's a strong opinion-haver who knows how things are supposed in 2022 and feels like then they can just own this repo without input from me / @EliAndrewC , that's okay too. Just reach out and we can set up permissions.

**Comment by sheromon** [comment]
@robdennis Sounds like a good plan and totally reasonable. I have a flexible schedule and nothing on my calendar other than some work meetings, so feel free to reach out here, over gmail, or whatever chat thing Google currently has if you'd like to pair up for a particular task or want to just break off a task for someone else.

**Comment by anoduck** [comment]
Back in business...

**Comment by robdennis** [comment]
5.0.7 is released out onto pypi. I am committing to fixing any errors that are associated with that release. After that point I think the README.md in the default branch (now ``release`` instead of ``master``) does correctly state that this project is not being actively maintained.

**Comment by kloczek** [comment]
I don;t see git 5.0.7 git tag in https://github.com/DiffSK/configobj/tags
Is it possible to tag that version in git repo? 🤔

**Comment by robdennis** [comment]
You’re right I didn’t tag / push the tag. Will correct that asap

**Comment by kloczek** [comment]
Thank you 👍 
SImple for me tags are important because I'm using autogenerated tar balls from git tags as input resources to build my packages 😋

**Comment by kloczek** [comment]
If may I ask next time to do one more thing 😋 
Could you please make next time release to have appeared tag on https://github.com/DiffSK/configobj/releases?
In this case my automation uses that as async signal delivered over SMTP ro try automatically build package 😄 
Github automation only takes releases to generate email notyfications ..

**Comment by kloczek** [comment]
Just tested 5.0.8 and looks like content of the src/validate/ is installed.
Is that intentional? 🤔

**Comment by anoduck** [comment]
I am so happy this beautiful library is back. 😃
