### ISSUE TITLE
Support for semicolon based comments

### ISSUE THREAD

**Issue by gau1991** [DiffSK/configobj#79]
Now PHP uses semicolon separted comments it its ini file. When I am trying to read php.ini file, I am getting error

```
>>> config = ConfigObj('/etc/php5/fpm/php.ini')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python3.4/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 3.
```

**Comment by gepd** [comment]
I've a file with ';' as market comment, I set the COMMENT_MARKERS with ['#', ';'] and when I write in the file, it ends with both markers

Ex. Initial comment:

; Comment Line 1
; Comment Line 2
After write in file:

# ; Comment Line 1
# ; Comment Line 2

I need to set both markers because some files I'm working with, starts with '#' and others ';'

**Comment by jhermann** [comment]
There are explicit tests for that, so your code does things differently than the test, or you use wrong versions. Check both.
