### ISSUE TITLE
Ignore duplicated keywords

### ISSUE THREAD

**Issue by meduvigo** [DiffSK/configobj#80]
Thanks for this library,

I suggest to leave the choice to skip or not duplicated keywords by creating a new Boolean specification called for example, duplicatekey = True/False.
Getting Exception: Duplicate keyword name at line ..

Regards.

**Comment by jhermann** [comment]
@meduvigo This seems to be a case where `.merge()` should be used (later read files overriding previously read values). Consider this example:

https://github.com/jhermann/rudiments/blob/9e23e8453014a65198b8aae5c5b151f6ed048609/src/rudiments/reamed/click.py#L172

If that is what you were after, please close, else comment with specifics.

**Comment by ryran** [comment]
I found this thread because someone introduced an error in how tons of config files were generated and we ended up with a bunch that had duplicate keys. In the end, I replaced configobj with my own parsing code, since our config files are simple `name=value` pairs and don't require all the fancy capabilities that configobj provides (like typing and validation and multi-line parsing, etc).

Based on my use-case, it seemed like a no-brainer to have an option for this, but @EliAndrewC thanks for explaining why it isn't. Your points are all valid and I get it now.

Anyway, thanks for a great project! I've used it here and there over the years with great success.
