### ISSUE TITLE
No doc/wiki about version 5

### ISSUE THREAD

**Issue by buhtz** [DiffSK/configobj#89]
Please update the documentation/wiki from version 4 to the current version 5. thx

**Comment by EliAndrewC** [comment]
The version 5 docs are online at http://configobj.readthedocs.org/ which is linked to from this Github and from PyPI.

Unfortunately, if you google for "configobj" the first two results are for the old docs by virtue of the fact that those websites (which the current maintainers don't own or control) have more Google pagerank than the newer docs.

Fortunately, those docs are still fine, as the 5.x releases haven't really added anything except Python 3 support, so those docs will have all of the correct info, so that's not too bad.

**Comment by buhtz** [comment]
I can not found any link to the 5-docs here on github. Where is it?

**Comment by EliAndrewC** [comment]
The "Documentation section on this project's homepage links to ReadTheDocs: https://github.com/DiffSK/configobj#documentation

**Comment by buhtz** [comment]
Ah I see. Thanks for the hint. No I understand the missunderstandings. ;)
I looked up in the wiki.

So then just bring the documentation up-to-date and consistent. Don't use multiple places (readdocs, github-wiki, ...) for the same issue. Decide for one place and link there from all the other possible places.
That would make it more clear for new users and contributers.

**Comment by EliAndrewC** [comment]
Whoops!  Good point about the wiki, I've done as you suggested and replaced the copy/paste of the outdated .rst source with a link to http://configobj.readthedocs.org/

Thanks for pointing that out; going forward I'll do as you suggest and make sure that any place where people would expect docs we'll link to the single canonical place (which will probably be Read the Docs for the forseeable future).

**Comment by jhermann** [comment]
@EliAndrewC editing the RTD link into the project summary (at the top of the project index page) makes it more visible.

**Comment by EliAndrewC** [comment]
Good point, I'll re-open this issue until I have time to make that quick fix.  Thanks for the suggestion.

**Comment by jhermann** [comment]
@EliAndrewC please make that quick fix. ;) I can't.

**Comment by EliAndrewC** [comment]
Done!
